services:
  dynamodb:
    image: amazon/dynamodb-local
    volumes:
      - dynamodb_data:/home/dynamodblocal
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin123
    ports:
      - "8000:8000"
    networks:
      - kanban

  api:
    build: ./backend
    depends_on:
      - dynamodb
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin123
    ports:
      - "8080:8080"
    networks:
      - kanban

  ui:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - kanban

networks:
  kanban:
    driver: bridge

volumes:
  dynamodb_data:
